import { ScoreThreshold, CriteriaGroup } from "@/components/underwriting/types";

export const initialScoreThresholds: ScoreThreshold[] = [
  { threshold: 9, color: "text-green-500" },
  { threshold: 7, color: "text-blue-500" },
  { threshold: 5, color: "text-yellow-500" },
  { threshold: 0, color: "text-red-500" }
];

export const initialCriteriaGroups: CriteriaGroup[] = [
  {
    name: "Financial Strength",
    description: "Measures the overall financial health of the borrower",
    weight: 25,
    minScore: 4.0,
    maxScore: 4.2,
    criteria: [
      {
        name: "DSCR Ratio",
        description: "Debt Service Coverage Ratio - measures ability to service debt",
        value: "1.8x",
        weight: 35,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        unit: "x",
        preferredMin: 1.5,
        preferredMax: 3.0,
        actualMin: 0,
        actualMax: 5,
        actualValue: 1.8,
        actualUnit: "x",
        enabled: true,
        scoreMapping: [
          { min: 3.00, max: 100, score: 10, riskLevel: "Exceptional" },
          { min: 2.50, max: 2.99, score: 9, riskLevel: "Very Strong" },
          { min: 2.00, max: 2.49, score: 8, riskLevel: "Strong" },
          { min: 1.75, max: 1.99, score: 7, riskLevel: "Good" },
          { min: 1.50, max: 1.74, score: 6, riskLevel: "Moderate" },
          { min: 1.25, max: 1.49, score: 5, riskLevel: "Acceptable" },
          { min: 1.10, max: 1.24, score: 4, riskLevel: "Weak" },
          { min: 1.00, max: 1.09, score: 3, riskLevel: "Very Weak" },
          { min: 0.75, max: 0.99, score: 2, riskLevel: "High Risk" },
          { min: 0, max: 0.75, score: 1, riskLevel: "Severe Risk" }
        ]
      },
      {
        name: "Debt/EBITDA",
        description: "Ratio of total debt to EBITDA",
        value: "3.6x",
        weight: 20,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        unit: "x",
        preferredMin: 2.0,
        preferredMax: 4.0,
        actualMin: 0,
        actualMax: 10,
        actualValue: 3.6,
        actualUnit: "x",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 1.00, score: 10, riskLevel: "Minimal Leverage" },
          { min: 1.01, max: 2.00, score: 9, riskLevel: "Low Leverage" },
          { min: 2.01, max: 3.00, score: 8, riskLevel: "Very Manageable" },
          { min: 3.01, max: 4.00, score: 7, riskLevel: "Moderate Risk" },
          { min: 4.01, max: 5.00, score: 6, riskLevel: "Slightly Elevated Risk" },
          { min: 5.01, max: 6.00, score: 5, riskLevel: "Cautionary" },
          { min: 6.01, max: 7.00, score: 4, riskLevel: "High Risk" },
          { min: 7.01, max: 8.00, score: 3, riskLevel: "Very High Risk" },
          { min: 8.01, max: 10.00, score: 2, riskLevel: "Distressed Leverage" },
          { min: 10.01, max: 100, score: 1, riskLevel: "Unsustainable" }
        ]
      },
      {
        name: "Current Ratio",
        description: "Current assets divided by current liabilities - measures short-term liquidity",
        value: "1.8x",
        weight: 20,
        minScore: 4,
        maxScore: 4,
        min: 0.5,
        max: 3.0,
        step: 0.1,
        unit: "x",
        preferredMin: 1.5,
        preferredMax: 3.0,
        actualMin: 0,
        actualMax: 5,
        actualValue: 1.8,
        actualUnit: "x",
        enabled: true,
        scoreMapping: [
          { min: 3.00, max: 100, score: 10, riskLevel: "Exceptional" },
          { min: 2.50, max: 2.99, score: 9, riskLevel: "Very Strong" },
          { min: 2.00, max: 2.49, score: 8, riskLevel: "Strong" },
          { min: 1.75, max: 1.99, score: 7, riskLevel: "Good" },
          { min: 1.50, max: 1.74, score: 6, riskLevel: "Moderate" },
          { min: 1.25, max: 1.49, score: 5, riskLevel: "Acceptable" },
          { min: 1.10, max: 1.24, score: 4, riskLevel: "Weak" },
          { min: 1.00, max: 1.09, score: 3, riskLevel: "Very Weak" },
          { min: 0.75, max: 0.99, score: 2, riskLevel: "High Risk" },
          { min: 0, max: 0.75, score: 1, riskLevel: "Severe Risk" }
        ]
      },
      {
        name: "Interest Coverage Ratio",
        description: "Measures how easily a company can pay interest on its outstanding debt",
        value: "4.2x",
        weight: 15,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        unit: "x",
        preferredMin: 3.5,
        preferredMax: 8.0,
        actualMin: 0,
        actualMax: 10,
        actualValue: 4.2,
        actualUnit: "x",
        enabled: true,
        scoreMapping: [
          { min: 8.00, max: 100, score: 10, riskLevel: "Outstanding" },
          { min: 6.00, max: 7.99, score: 9, riskLevel: "Very Strong" },
          { min: 4.50, max: 5.99, score: 8, riskLevel: "Strong" },
          { min: 3.50, max: 4.49, score: 7, riskLevel: "Good" },
          { min: 2.75, max: 3.49, score: 6, riskLevel: "Moderate" },
          { min: 2.00, max: 2.74, score: 5, riskLevel: "Acceptable" },
          { min: 1.50, max: 1.99, score: 4, riskLevel: "Weak" },
          { min: 1.00, max: 1.49, score: 3, riskLevel: "Very Weak" },
          { min: 0.75, max: 0.99, score: 2, riskLevel: "High Risk" },
          { min: 0, max: 0.75, score: 1, riskLevel: "Severe Risk" }
        ]
      },
      {
        name: "Quick Ratio",
        description: "Measures a company's ability to pay short-term obligations with its most liquid assets",
        value: "10.5",
        weight: 15,
        minScore: 6,
        maxScore: 6,
        min: 1,
        max: 10,
        step: 1,
        unit: "",
        preferredMin: 8,
        preferredMax: 16,
        actualMin: 0,
        actualMax: 20,
        actualValue: 10.5,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 18.00, max: 20.00, score: 10, riskLevel: "Exceptionally Liquid" },
          { min: 16.00, max: 17.99, score: 9, riskLevel: "Extremely Liquid" },
          { min: 14.00, max: 15.99, score: 8, riskLevel: "Very Liquid" },
          { min: 12.00, max: 13.99, score: 7, riskLevel: "Highly Liquid" },
          { min: 10.00, max: 11.99, score: 6, riskLevel: "Good Liquidity" },
          { min: 8.00, max: 9.99, score: 5, riskLevel: "Moderate Liquidity" },
          { min: 6.00, max: 7.99, score: 4, riskLevel: "Fair Liquidity" },
          { min: 4.00, max: 5.99, score: 3, riskLevel: "Low Liquidity" },
          { min: 2.00, max: 3.99, score: 2, riskLevel: "Very Low Liquidity" },
          { min: 0, max: 1.99, score: 1, riskLevel: "Critical Liquidity" }
        ]
      }
    ]
  },
  {
    name: "Business Stability",
    description: "Evaluates the operational stability of the business",
    weight: 20,
    minScore: 3.3,
    maxScore: 3.5,
    criteria: [
      {
        name: "Years in Business",
        description: "Number of years since company founding",
        value: "14 years",
        weight: 35,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 30,
        actualValue: 14,
        actualUnit: " years",
        enabled: true,
        scoreMapping: [
          { min: 15.00, max: 30.00, score: 10, riskLevel: "Exceptional" },
          { min: 10.00, max: 14.99, score: 9, riskLevel: "Very Strong" },
          { min: 7.00, max: 9.99, score: 8, riskLevel: "Strong" },
          { min: 5.00, max: 6.99, score: 7, riskLevel: "Good" },
          { min: 3.00, max: 4.99, score: 6, riskLevel: "Moderate" },
          { min: 2.00, max: 2.99, score: 5, riskLevel: "Acceptable" },
          { min: 1.00, max: 1.99, score: 4, riskLevel: "Weak" },
          { min: 0.50, max: 0.99, score: 3, riskLevel: "Very Weak" },
          { min: 0.25, max: 0.49, score: 2, riskLevel: "High Risk" },
          { min: 0, max: 0.24, score: 1, riskLevel: "Severe Risk" }
        ]
      },
      {
        name: "Revenue Concentration",
        description: "Dependency on key customers",
        value: "32%",
        weight: 25,
        minScore: 3,
        maxScore: 3,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 100,
        actualValue: 32,
        actualUnit: "%",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 10, score: 10, riskLevel: "Highly Diversified" },
          { min: 10, max: 15, score: 9, riskLevel: "Very Diversified" },
          { min: 15, max: 20, score: 8, riskLevel: "Well Diversified" },
          { min: 20, max: 25, score: 7, riskLevel: "Good Diversification" },
          { min: 25, max: 30, score: 6, riskLevel: "Moderate Diversification" },
          { min: 30, max: 40, score: 5, riskLevel: "Acceptable Diversification" },
          { min: 40, max: 50, score: 4, riskLevel: "Limited Diversification" },
          { min: 50, max: 60, score: 3, riskLevel: "Poor Diversification" },
          { min: 60, max: 75, score: 2, riskLevel: "Very Concentrated" },
          { min: 75, max: 100, score: 1, riskLevel: "Extremely Concentrated" }
        ]
      },
      {
        name: "Geographic Footprint",
        description: "Regional diversity of operations",
        value: "7 states",
        weight: 40,
        minScore: 3,
        maxScore: 3,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 20,
        actualValue: 7,
        actualUnit: " states",
        enabled: true,
        scoreMapping: [
          { min: 12, max: 50, score: 10, riskLevel: "National/International" },
          { min: 10, max: 11.99, score: 9, riskLevel: "Multi-Regional" },
          { min: 8, max: 9.99, score: 8, riskLevel: "Broad Regional" },
          { min: 7, max: 7.99, score: 7, riskLevel: "Regional" },
          { min: 5, max: 6.99, score: 6, riskLevel: "Limited Regional" },
          { min: 3, max: 4.99, score: 5, riskLevel: "Multi-State" },
          { min: 2, max: 2.99, score: 4, riskLevel: "Dual-State" },
          { min: 1, max: 1.99, score: 3, riskLevel: "Single State" },
          { min: 0.5, max: 0.99, score: 2, riskLevel: "Metropolitan Area" },
          { min: 0, max: 0.49, score: 1, riskLevel: "Local Only" }
        ]
      }
    ]
  },
  {
    name: "Competitive Positioning",
    description: "Evaluates market position relative to competitors",
    weight: 15,
    minScore: 4.3,
    maxScore: 4.4,
    criteria: [
      {
        name: "Market Share",
        description: "Percentage of total addressable market",
        value: "7%",
        weight: 30,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 25,
        actualValue: 7,
        actualUnit: "%",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 1, score: 1 },
          { min: 1, max: 3, score: 2 },
          { min: 3, max: 5, score: 3 },
          { min: 5, max: 10, score: 4 },
          { min: 10, max: 100, score: 5 }
        ]
      },
      {
        name: "Differentiation Score",
        description: "Uniqueness of product/service offering",
        value: "High",
        weight: 35,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 1,
        actualMax: 10,
        actualValue: 8,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 1, max: 3, score: 1 },
          { min: 3, max: 5, score: 2 },
          { min: 5, max: 6, score: 3 },
          { min: 6, max: 8, score: 4 },
          { min: 8, max: 10, score: 5 }
        ]
      },
      {
        name: "Barrier to Entry Score",
        description: "Difficulty for new competitors to enter market",
        value: "Medium-High",
        weight: 35,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 1,
        actualMax: 10,
        actualValue: 7,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 1, max: 3, score: 1 },
          { min: 3, max: 5, score: 2 },
          { min: 5, max: 6, score: 3 },
          { min: 6, max: 8, score: 4 },
          { min: 8, max: 10, score: 5 }
        ]
      }
    ]
  },
  {
    name: "Management Strength",
    description: "Assesses the experience and capability of leadership team",
    weight: 15,
    minScore: 4.8,
    maxScore: 4.9,
    criteria: [
      {
        name: "Leadership Depth",
        description: "Experience level of management team",
        value: "Very High",
        weight: 40,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 1,
        actualMax: 10,
        actualValue: 9,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 1, max: 3, score: 1 },
          { min: 3, max: 5, score: 2 },
          { min: 5, max: 6, score: 3 },
          { min: 6, max: 8, score: 4 },
          { min: 8, max: 10, score: 5 }
        ]
      },
      {
        name: "Ownership/Management Alignment",
        description: "Alignment between ownership and management",
        value: "High",
        weight: 30,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 1,
        actualMax: 10,
        actualValue: 8,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 1, max: 3, score: 1 },
          { min: 3, max: 5, score: 2 },
          { min: 5, max: 6, score: 3 },
          { min: 6, max: 8, score: 4 },
          { min: 8, max: 10, score: 5 }
        ]
      },
      {
        name: "Succession Plan",
        description: "Quality of transition planning",
        value: "Moderate",
        weight: 30,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 1,
        actualMax: 10,
        actualValue: 7,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 1, max: 3, score: 1 },
          { min: 3, max: 5, score: 2 },
          { min: 5, max: 6, score: 3 },
          { min: 6, max: 8, score: 4 },
          { min: 8, max: 10, score: 5 }
        ]
      }
    ]
  },
  {
    name: "Industry & Market Risk",
    description: "Evaluates sector-specific risks and market dynamics",
    weight: 25,
    minScore: 3.6,
    maxScore: 3.7,
    criteria: [
      {
        name: "Industry Volatility",
        description: "Historical stability of the industry",
        value: "Moderate",
        weight: 30,
        minScore: 3,
        maxScore: 3,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 3,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      },
      {
        name: "Market Growth",
        description: "Projected growth rate of target market",
        value: "Growing/Predictable",
        weight: 40,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 4,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      },
      {
        name: "Regulatory Risk",
        description: "Exposure to regulatory changes",
        value: "Moderate-High",
        weight: 30,
        minScore: 3,
        maxScore: 3,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 3,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      }
    ]
  },
  {
    name: "Covenant Health",
    description: "Compliance with existing loan covenants",
    weight: 15,
    minScore: 4.7,
    maxScore: 4.8,
    criteria: [
      {
        name: "Covenant Compliance",
        description: "Historical compliance with financial covenants",
        value: "High",
        weight: 40,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 5,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      },
      {
        name: "Primary Banking Relationship",
        description: "Strength of primary banking relationship",
        value: "Strong",
        weight: 20,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 5,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      },
      {
        name: "Payment History",
        description: "Historical payment performance",
        value: "Excellent",
        weight: 20,
        minScore: 5,
        maxScore: 5,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 5,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      },
      {
        name: "Covenant Flexibility",
        description: "Flexibility within existing covenant structure",
        value: "Medium",
        weight: 20,
        minScore: 4,
        maxScore: 4,
        min: 1,
        max: 5,
        step: 1,
        actualMin: 0,
        actualMax: 10,
        actualValue: 4,
        actualUnit: "",
        enabled: true,
        scoreMapping: [
          { min: 0, max: 2, score: 5 },
          { min: 2, max: 4, score: 4 },
          { min: 4, max: 6, score: 3 },
          { min: 6, max: 8, score: 2 },
          { min: 8, max: 10, score: 1 }
        ]
      }
    ]
  }
];
